language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:

install:
  - wget http://downloads.sourceforge.net/libxls/libxls-0.2.0.tar.gz
  - tar -xzvf libxls-0.2.0.tar.gz
  - cd libxls-0.2.0
  - ./configure --prefix=$HOME
  - make
  - make install
  - go get github.com/northbright/pathhelper

before_script:
  - export LD_LIBRARY_PATH="$HOME/lib":$LD_LIBRARY_PATH

script:
  - cd ../xls2csv
  - CGO_CFLAGS="-I$HOME/include" CGO_LDFLAGS="-L$HOME/lib -lxlsreader" go test -c && ./xls2csv.test
