sudo: required

language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - ./install-libxls.sh

install:
  - go get github.com/northbright/pathhelper

script:
  - cd xls2csv
  - LD_LIBRARY_PATH="/usr/local/libxls/lib/" CGO_CFLAGS="-I/usr/local/libxls/include" CGO_LDFLAGS="-L/usr/local/libxls/lib -lxlsreader" go test -c && ./xls2csv.test
